# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Minimal blog
email: blogminimal@minimal.com
description: "Esse é um blog minimalista criado no curso Jekyll por Willian Justen em 22.04.16"
baseurl: "/my_blog" # the subpath of your site, e.g. /blog
url: "http://cmpereira.com.br" # the base hostname & protocol for your site
twitter_username: cmpereira.si
github_username:  cmpereirasi

# Build settings
markdown: kramdown
permalink: /:year/:month/:day/:title
